export const ESorTrades = [
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "ADAP",
        "ElementCode": "FLASHDB",
        "EffDate": "2016-05-26",
        "TradeCode": "AL",
        "MainTrade": false,
        "Smv": 30,
        "TradeDescription": "",
        "id": "01|HSG|ADAP|FLASHDB|26/05/16|AL",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "ADAP",
        "ElementCode": "FLASHDB",
        "EffDate": "2016-05-26",
        "TradeCode": "AT",
        "MainTrade": true,
        "Smv": 30,
        "TradeDescription": "",
        "id": "01|HSG|ADAP|FLASHDB|26/05/16|AT",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "ADAP",
        "ElementCode": "FLASHDB",
        "EffDate": "2016-05-26",
        "TradeCode": "EL",
        "MainTrade": false,
        "Smv": 30,
        "TradeDescription": "Electrician",
        "id": "01|HSG|ADAP|FLASHDB|26/05/16|EL",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "ADAP",
        "ElementCode": "HANDBATH",
        "EffDate": "2016-05-26",
        "TradeCode": "AT",
        "MainTrade": true,
        "Smv": 45,
        "TradeDescription": "",
        "id": "01|HSG|ADAP|HANDBATH|26/05/16|AT",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "ADAP",
        "ElementCode": "RAMPRR",
        "EffDate": "2016-05-26",
        "TradeCode": "AT",
        "MainTrade": true,
        "Smv": 60,
        "TradeDescription": "",
        "id": "01|HSG|ADAP|RAMPRR|26/05/16|AT",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "ADAP",
        "ElementCode": "RMAPFRT",
        "EffDate": "2016-05-26",
        "TradeCode": "AT",
        "MainTrade": true,
        "Smv": 60,
        "TradeDescription": "",
        "id": "01|HSG|ADAP|RMAPFRT|26/05/16|AT",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101101",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 33,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101101|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101101",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101101|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101103",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 50,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101103|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101103",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101103|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101105",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 84,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101105|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101105",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101105|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101107",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 48,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101107|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101107",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101107|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101109",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 20,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101109|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101109",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101109|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101111",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 30,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101111|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101111",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101111|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101121",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 50,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101121|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101121",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101121|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101123",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 75,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101123|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101123",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101123|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101301",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 110,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101301|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101301",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101301|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101303",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 175,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101303|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101303",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101303|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101305",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 240,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101305|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101305",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101305|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101307",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 200,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101307|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101307",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101307|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101309",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 150,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101309|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101309",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101309|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101311",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 250,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101311|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101311",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101311|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101313",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 260,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101313|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101313",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101313|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101315",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 70,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101315|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101315",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101315|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101317",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 75,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101317|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101317",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101317|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101319",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 120,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101319|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101319",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101319|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101501",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 60,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101501|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101501",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101501|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101503",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 230,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101503|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101503",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101503|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101505",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 185,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101505|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101505",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101505|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101507",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 300,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101507|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101507",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101507|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101509",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 80,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101509|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101509",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101509|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101511",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 90,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101511|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101511",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101511|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101513",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 135,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101513|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101513",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101513|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101515",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 300,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101515|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101515",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101515|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101517",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 300,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101517|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101517",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101517|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101601",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 50,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101601|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101601",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101601|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101603",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 35,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101603|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101603",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101603|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101701",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 40,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101701|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101701",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101701|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101703",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 200,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101703|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101703",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101703|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101705",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 75,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101705|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101705",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101705|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101707",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 250,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101707|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101707",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101707|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101709",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 55,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101709|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101709",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101709|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101711",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 220,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101711|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101711",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101711|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101713",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 95,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101713|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101713",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101713|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101715",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 285,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101715|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101715",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101715|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101901",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 120,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101901|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101901",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101901|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101903",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 50,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101903|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101903",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101903|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101905",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 250,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101905|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101905",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101905|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101907",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 55,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101907|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101907",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101907|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101909",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 275,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101909|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101909",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101909|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101911",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 15,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101911|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101911",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101911|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101913",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 10,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101913|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101913",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101913|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101915",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 25,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101915|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101915",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101915|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101917",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 20,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|101917|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "101917",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|101917|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102103",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 60,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102103|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102103",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102103|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102105",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 8,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102105|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102105",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102105|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102201",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 255,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102201|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102201",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102201|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102203",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 315,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102203|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102203",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102203|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102205",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 350,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102205|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102205",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102205|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102207",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 435,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102207|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102207",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102207|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102211",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 160,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102211|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102211",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102211|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102213",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 200,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102213|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102213",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102213|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102215",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 225,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102215|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102215",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102215|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102217",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 280,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102217|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102217",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102217|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102219",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 285,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102219|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102219",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102219|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102221",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 210,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102221|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102221",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102221|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102223",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 60,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102223|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102223",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102223|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102225",
        "EffDate": "2014-01-01",
        "TradeCode": "MS",
        "MainTrade": true,
        "Smv": 100,
        "TradeDescription": "Masonry",
        "id": "01|HSG|BCBC|102225|01/01/14|MS",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102225",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102225|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102301",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 10,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102301|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102301",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102301|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102503",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 155,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102503|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102503",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102503|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102719",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 15,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102719|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102719",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102719|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102721",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 8,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102721|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102721",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102721|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102731",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 300,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102731|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102731",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102731|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102733",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 390,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102733|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102733",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102733|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102741",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 330,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102741|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102741",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102741|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102743",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 400,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102743|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102743",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102743|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102745",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 570,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102745|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102745",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102745|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102751",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 300,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102751|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102751",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102751|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102753",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 310,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102753|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102753",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102753|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102761",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 250,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102761|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102761",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102761|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102763",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 255,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102763|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102763",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102763|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102765",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 280,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102765|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102765",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102765|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102771",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 245,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102771|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102771",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102771|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102773",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 255,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102773|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102773",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102773|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102901",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 180,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102901|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102901",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102901|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102903",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 240,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102903|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102903",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102903|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102905",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 245,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102905|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102905",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102905|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102907",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 315,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102907|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102907",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102907|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102909",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 620,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102909|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102909",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102909|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102911",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 245,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102911|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102911",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102911|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102913",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 480,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|102913|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "102913",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|102913|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103101",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 25,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103101|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103101",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103101|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103103",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 85,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103103|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103103",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103103|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103105",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 110,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103105|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103105",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103105|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103107",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 70,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103107|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103107",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103107|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103109",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 9,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103109|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103109",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103109|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103111",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 65,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103111|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103111",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103111|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103113",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 80,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103113|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103113",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103113|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103115",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 60,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103115|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103115",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103115|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103117",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 75,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103117|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103117",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103117|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103119",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 75,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103119|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103119",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103119|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103121",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 135,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103121|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103121",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103121|01/01/14|No",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103301",
        "EffDate": "2014-01-01",
        "TradeCode": "BR",
        "MainTrade": true,
        "Smv": 9,
        "TradeDescription": "Brick Workaaa",
        "id": "01|HSG|BCBC|103301|01/01/14|BR",
        "seq": null
    },
    {
        "OrgCode": "01",
        "ClientCode": "HSG",
        "Contract": "BCBC",
        "ElementCode": "103301",
        "EffDate": "2014-01-01",
        "TradeCode": "No",
        "MainTrade": false,
        "Smv": 0,
        "TradeDescription": "",
        "id": "01|HSG|BCBC|103301|01/01/14|No",
        "seq": null
    }
]
